Hardware_Inventory.Web/Models/Colleague.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Hardware_Inventory.Web.Models
{
    //form modell
    public class Colleague
    {
        [Display(Name = "Registrational number")]
        public int ID { get; set; }
        
        [Display(Name ="Full name of the colleague")]
        [Required]
        [StringLength(40,MinimumLength =5)]
        public string Name { get; set; }

        [Display(Name ="Mail where he can be reached, be it work or personal")]
        [Required]
        [EmailAddress]
        public string Mail { get; set; }

        [Display(Name="At which facility he is working at")]
        [Required]
        public string Workplace { get; set; }

        [Display(Name="Post of the colleague")]
        [Required]
        public string Post { get; set; }
    }
}

Hardware_Inventory.Web/Models/ColleaguesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hardware_Inventory.Web.Models
{
    public class ColleaguesViewModel
    {
        public Colleague EditedColleague { get; set; }

        public List<Colleague> ListOfColleagues { get; set; }
    }
}

Hardware_Inventory.Web/Controllers/ColleaguesController.cs
using AutoMapper;
using Hardware_Inventory.BL.Interfaces;
using Hardware_Inventory.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Hardware_Inventory.Repository.Repositories;
using Hardware_Inventory.BL.Services;
using Hardware_Inventory.Web;
using Hardware_Inventory.DA;

namespace Hardware_Inventory.Web.Views
{
    public class ColleaguesController : Controller
    {
        ColleagueService logic;
        IMapper mapper;
        ColleaguesViewModel vm;

        public ColleaguesController()
        {
            ColleaguesRepository ColleagueRepo = new ColleaguesRepository();
            logic = new ColleagueService(ColleagueRepo);
            mapper = MapperFactory.CreateMapper();

            vm = new ColleaguesViewModel();
            vm.EditedColleague = new Colleague();
            var AllColleagues = logic.GetAll();
            vm.ListOfColleagues = mapper.Map<IList<DA.colleagues>, List<Web.Models.Colleague>>(AllColleagues);

        }

        private Colleague GetColleague(int id)
        {
            colleagues oneColleague = logic.GetColleagueByID(id);
            return mapper.Map<Hardware_Inventory.DA.colleagues, Models.Colleague>(oneColleague);

        }

        // GET: Colleagues
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("ColleagueIndex", vm);
        }

        // GET: Colleagues/Details/5
        public ActionResult Details(int id)
        {
            return View("ColleagueDetails",GetColleague(id));
        }

        // GET: Colleagues/Delete/5
        public ActionResult Delete(int id)
        {
            TempData["editResult"] = "Delete FAILED";
            logic.Delete(id);           
            if (logic.GetColleagueByID(id)==null) TempData["editResult"] = "Succesfully deleted";
            return RedirectToAction(nameof(Index));
        }

        // GET: Colleagues/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedColleague = GetColleague(id);
            return View("ColleagueIndex", vm);
        }

        /// Post: Colleagues/Edit/5
        [HttpPost]
        public ActionResult Edit(Colleague colleague, string editAction)
        {
            if (ModelState.IsValid && colleague != null)
            {
                if (editAction == "AddNew")
                {
                    logic.AddNewColleague(new colleagues() { Full_Name = colleague.Name, Email = colleague.Mail, Post = colleague.Post, WorksAt = colleague.Workplace });
                }
                else
                {
                    if(logic.UpdateColleague(new colleagues() { Users_ID = colleague.ID, Full_Name = colleague.Name, Email = colleague.Mail, Post = colleague.Post, WorksAt = colleague.Workplace }))
                        TempData["editResult"] = "Edited Succesfully";
                    else
                        TempData["editResult"] = "Edit Failed";
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedColleague = colleague;
                return View("ColleagueIndex", vm);
            }
        }
    }
}

Hardware_Inventory.Web/Views/Colleagues/ColleagueDetails.cshtml
@model Hardware_Inventory.Web.Models.Colleague
@{
    ViewBag.Title = "ColleagueDetails";
}

<h2>Datasheet for @Model.Name</h2>

@Html.ActionLink("Back to the list", "Index");

<table>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Model.Name </td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.ID)</td>
        <td>@Model.ID </td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Mail)</td>
        <td>@Model.Mail </td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Post)</td>
        <td>@Model.Post </td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Workplace)</td>
        <td>@Model.Workplace </td>
    </tr>
</table>

Hardware_Inventory.Web/Views/Colleagues/ColleagueEdit.cshtml
@model Hardware_Inventory.Web.Models.Colleague

<h2>Edit colleague details</h2>

<h3>Colleague ID: @Model.ID - This can't be changed.</h3>

@using (Html.BeginForm("Edit", "Colleagues"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.ID)
    @Html.Hidden("editAction",ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Mail)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Mail)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Post)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Post)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Workplace)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Workplace)</div>

    <input type="submit" value="SAVE"/>
}

Hardware_Inventory.Web/Views/Colleagues/ColleagueIndex.cshtml
@model Hardware_Inventory.Web.Models.ColleaguesViewModel
@{
    ViewBag.Title = "ColleagueIndex";
}

<h2>ColleagueIndex</h2>

<p style="color:red; font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("ColleagueEdit", Model.EditedColleague)

@Html.Partial("ColleagueList", Model.ListOfColleagues)

Hardware_Inventory.Web/Views/Colleagues/ColleagueList.cshtml
@model IEnumerable<Hardware_Inventory.Web.Models.Colleague>

<h2>List of Colleagues</h2>

@if (Model.Count() == 0)
{
    <p>No Data found</p>
}
else
{
    <table border="1">
        <tr>
        <th>@Html.DisplayNameFor(m => m.First().Name)</th>
        <th>@Html.DisplayNameFor(m => m.First().Post)</th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(m=>item.Name)</td>
            <td>@Html.DisplayFor(m => item.Post)</td>
            <td>@Html.ActionLink("[Check datasheet]","Details",new { id = item.ID })</td>
            <td>@Html.ActionLink("[Promote to Costumer]", "Delete", new { id = item.ID })</td>
            <td>@Html.ActionLink("[Manage Colleague]", "Edit", new { id = item.ID })</td>
        </tr>
        }
    </table>
}